version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/restaurant_db
      - JWT_SECRET=your_jwt_secret
      - OTHER_ENV_VARS=values

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restaurant_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: